version: "3.8"
services:
  database:
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./scripts/docker/postgres/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: cloud
      POSTGRES_MULTIPLE_DATABASES: userdb,userdb_test,departmentdb,departmentdb_test
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
      PGDATA: /var/lib/postgresql/data/cloud
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "127.0.0.1:9411:9411"